/**
 * Tabla de multiplicadores de precio por cliente.
 * Se usa al crear un cliente nuevo desde Colppy para precargar el multiplicador.
 * La clave es la razón social exacta como viene de Colppy.
 */
export const CLIENT_MULTIPLIERS: Record<string, number> = {
  "A EVANGELISTA S A": 1.30,
  "ACHERAL S.A.": 1.11,
  "ADEA ADMINISTRADORA DE ARCHIVOS SA": 1.10,
  "AGRICULTORES FEDERADOS ARGENTINOS SOC COOP LTDA": 1.21,
  "AGROFINA S A": 1.10,
  "AGUA Y SANEAMIENTOS ARGENTINOS SOCIEDAD ANONIMA": 1.45,
  "AGUAS BONAERENSES S.A.": 1.45,
  "ALUAR ALUMINIO ARGENTINO SOCIEDAD ANONIMA INDUSTRIAL Y COMERCIAL": 1.30,
  "ANTARES NAVIERA SOCIEDAD ANONIMA": 1.11,
  "ARTE GRAFICO EDITORIAL ARGENTINO S A": 1.10,
  "ASOCIACION DE LOS TESTIGOS DE JEHOVA": 1.10,
  "ATANOR SOCIEDAD EN COMANDITA POR ACCIONES": 1.10,
  "AUSTIN POWDER ARGENTINA S A": 1.10,
  "AZUL NATURAL BEEF S.A.": 1.11,
  "BACS SOCIEDAD ANONIMA": 1.10,
  "BELGRANO CARGAS Y LOGISTICA SA": 1.10,
  "BENITO ROGGIO E HIJOS S.A.-JOSE CARTELLONE CONSTRUCCIONES CIV.S.A.-SUPERCEMENTO S.A.I.YC. UTE": 1.11,
  "BIO TRINIDAD SOCIEDAD ANONIMA": 1.04,
  "BIOELECTRICA DOS S.A": 1.10,
  "BIOSIDUS SOCIEDAD ANONIMA": 1.21,
  "BOMBAS GRUNDFOS DE ARGENTINA S.A.U": 1.10,
  "CARTELLONE OIL&GAS S.A.U.": 1.20,
  "CENTRAL COSTANERA S.A.": 1.20,
  "CENTRAL DOCK SUD SOCIEDAD ANONIMA": 1.10,
  "CENTRAL PUERTO S A": 1.20,
  "CENTRAL TERMICA ROCA S.A.": 1.20,
  "CENTRALES DE LA COSTA ATLANTICA SA": 1.21,
  "CERAMICA ALBERDI S A": 1.21,
  "CITROMAX SOCIEDAD ANONIMA COMERCIAL E INDUSTRIAL": 1.10,
  "CITRUSVIL S.A.": 1.10,
  "CLUB ATLETICO RIVER PLATE ASOC CIVIL": 1.10,
  "COLORTEX S A": 1.05,
  "COMPANIA INVERSORA INDUSTRIAL S.A.": 1.15,
  "COMPAÑIA ARGENTINA DE LEVADURAS S A I C": 1.15,
  "COMPAÑIA NAVIOS ARGENTINA S.A.": 1.10,
  "CONSTRUCTORA SUDAMERICANA S A C I F INMOB Y AGROP": 1.10,
  "COORDINACION ECOLOGICA AREA METROPOLITANA SOCIEDAD DEL ESTADO": 1.11,
  "COTEMINAS ARGENTINA SOCIEDAD ANONIMA": 1.06,
  "COTO CENTRO INTEGRAL DE COMERCIALIZACION SOCIEDAD ANONIMA": 1.20,
  "CR CONSTRUCTORA SRL": 1.10,
  "CT BARRAGAN S.A.": 1.11,
  "CULLIGAN ARGENTINA SOCIEDAD ANONIMA": 1.10,
  "DANIEL RICCA SA": 1.10,
  "DECAVIAL S.A.I.C.A.C.": 1.10,
  "DECAVIAL S.A.I.C.A.C. - ESUCO S.A. - SUPERCEMENTO S.A.I.C. - FIORITO - UTE": 1.10,
  "DECAVIAL SAICAC": 1.10,
  "DECAVIAL SAICAC - ESUCO SA - RP 46 - UTE": 1.10,
  "DEL PLATA INGENIERIA S A": 1.10,
  "DESTILERIA ARGENTINA DE PETROLEO SA": 1.10,
  "ECO MINERA S A": 1.21,
  "EMPRESA DISTRIBUIDORA Y COMERCIALIZADORA NORTE SOCIEDAD ANONIMA (EDENOR S A)": 1.15,
  "ENEL GENERACION COSTANERA SOCIEDAD ANONIMA": 1.18,
  "ESTABLECIMIENTO FRIGORIFICO AZUL S A": 1.11,
  "ESTREMAR S.A.U.": 1.11,
  "ETERNIT ARGENTINA SA": 1.15,
  "F V SOCIEDAD ANONIMA": 1.10,
  "FADEL  SA": 1.11,
  "FATE SAICI": 1.30,
  "FIDEICOMISO TRINIDAD": 1.04,
  "FRIGOLAR S. A.": 1.11,
  "FRIGORIFICO COSTANZO S A": 1.11,
  "FRIGORIFICO DE AVES SOYCHU SAICFIA": 1.11,
  "FRIGORIFICO EL BIERZO S A": 1.11,
  "FRIGORIFICO FAIMALI SOCIEDAD ANONIMA": 1.11,
  "FRIGORIFICO GENERAL PICO S A": 1.11,
  "FRIGORIFICO GORINA S A I C": 1.15,
  "FRIGORIFICO INDUSTRIAL DEL NORTE SA": 1.11,
  "FRIGORIFICO LAMAR S A": 1.11,
  "FRIGORIFICO MARK S.A.": 1.11,
  "FRIGORIFICO MONTECARLO SA": 1.11,
  "FRIGORIFICO RIOPLATENSE S A I C I F": 1.11,
  "FRIGORIFICO SAN AGUSTIN SRL": 1.11,
  "FUEGOTECNIC S R L": 1.05,
  "GALAN LITIO S. A.": 1.21,
  "GEA FARM TECHNOLOGIES ARGENTINA S R L": 1.10,
  "GEA PROCESS ENGINEERING SA": 1.10,
  "GENERACION MEDITERRANEA S.A.": 1.20,
  "GERARDO RAMON Y CIA S A I C": 1.10,
  "GRUPO COMECA (ARGENTINA) SA": 1.20,
  "HEMPEL ARGENTINA S R L": 1.10,
  "HENN Y CIA SRL": 1.15,
  "HIDRAULICA CVC S.A.S.": 1.10,
  "HOERBIGER DE ARGENTINA SA": 1.02,
  "INDUSTRIAS METALURGICAS PESCARMONA SAICF": 1.10,
  "INDUSTRIAS QUIMICAS Y MINERAS TIMBO SA": 1.21,
  "INFA SOCIEDAD ANONIMA": 1.21,
  "INGENIERIA BERNOULLI S.A.": 1.10,
  "INNOVACION TECNICA TOTAL S.A.": 1.10,
  "INQUINAT SA": 1.05,
  "INVAP SE": 1.10,
  "JUGOS S A": 1.10,
  "KLEPPE SA": 1.10,
  "KSB ARGENTINA S. A.": 1.15,
  "LABORATORIOS POEN SOCIEDAD ANONIMA COMERCIAL INDUSTRIAL FINANCIERA E INMOBILIARI": 1.10,
  "LACTEOS CONOSUR S A": 1.10,
  "LIEX S.A.": 1.21,
  "LITIO MINERA ARGENTINA SOCIEDAD ANONIMA": 1.21,
  "LUBRICANTES AVELLANEDA S.A.U.": 1.10,
  "LUIS ALBERTO SABOREDO": 1.11,
  "M ROYO S. A.": 1.20,
  "MAN SER SOCIEDAD DE RESPONSABILIDAD LIMITADA": 1.10,
  "MANSFIELD MINERA  S A": 1.21,
  "MANUEL SANMARTIN S A": 1.20,
  "MATADERO Y FRIGORIFICO MERLO SA": 1.11,
  "MAURO PAUL SUAREZ": 1.10,
  "MEGA ENERGIAS SA": 1.10,
  "MINERA DEL ALTIPLANO S A": 1.21,
  "MINERA EXAR SA": 1.21,
  "MINERA SANTA CRUZ S.A": 1.21,
  "MINERA SANTA RITA SRL": 1.21,
  "MINERA TEA S A M I C A Y F": 1.21,
  "MINERAR SA": 1.21,
  "MIRBLA S A": 1.10,
  "MOLINO CAÑUELAS SOCIEDAD ANONIMA COMERCIAL INDUSTRIAL  FINANCIERA INMOBILIARIA Y AGROPECUARIA": 1.25,
  "MORIXE HERMANOS SOCIEDAD ANONIMA COMERCIAL E INDUSTRIAL": 1.11,
  "MSU ENERGY S.A.": 1.10,
  "NEWSAN SOCIEDAD ANONIMA": 1.21,
  "OILFIELD SERVICES S.A.": 1.21,
  "OLIGRA SUDAMERICANA S.A.": 1.10,
  "PALMERO SAN LUIS SA": 1.10,
  "PAMPA ENERGIA S A": 1.10,
  "PAN AMERICAN ENERGY, S.L.,  SUCURSAL ARGENTINA": 1.10,
  "PANEDILE ARGENTINA S.A.I.C.F. E I. - ROVELLA CARRANZA S.A. - ELEPRINT S.A. - COARCO S.A. UTE": 1.10,
  "PANEDILE ARGENTINA S.A.I.C.F.E I. - ESUCO S.A - ECOPRENEUR S.A. - UNION TRANSITORIA": 1.10,
  "PANEDILE ARGENTINA SA IND COM FIN EINMOB": 1.10,
  "PAPELERA DEL NOA SA": 1.20,
  "PAPELERA SAMSENG SA": 1.10,
  "PATAGONIA GOLD S.A.": 1.21,
  "PEHUENCHE S R L": 1.11,
  "PRAXAIR ARGENTINA SOCIEDAD DE RESPONSABILIDAD LIMITADA": 1.18,
  "PRYSMIAN ENERGIA CABLES Y SISTEMAS DE ARG. SA": 1.21,
  "PUNA MINING S.A.": 1.21,
  "QUERUCLOR SRL": 1.10,
  "QUICKFOOD S A": 1.21,
  "QUIMICA MONTPELLIER S A": 1.10,
  "QUIMICA OESTE SOCIEDAD ANONIMA": 1.10,
  "RAFAEL G ALBANESI  SOCIEDAD ANONIMA": 1.20,
  "REFINERIAS DE GRASAS SUDAMERICANA S.A.": 1.15,
  "RICARDO SIXTO ANSONNAUD": 1.04,
  "RIS SOCIEDAD ANONIMA": 1.11,
  "S.N.F. ARGENTINA S.R.L.": 1.10,
  "SACDE SOCIEDAD ARGENTINA DE CONSTRUCCION Y DESARROLLO ESTRATEGICO S.A.": 1.10,
  "SALES DE JUJUY SOCIEDAD ANONIMA": 1.21,
  "SALTA REFRESCOS S A": 1.11,
  "SERVICIOS Y PRODUCTOS PARA BEBIDAS REFRESCANTES SOCIEDAD DE RESPONSABILIDAD LIMITADA": 1.10,
  "SIAT SOCIEDAD ANONIMA": 1.21,
  "SIDERCA S A I C": 1.21,
  "SIDUS SOCIEDAD ANONIMA": 1.10,
  "SILVATEAM ENERGIAS RENOVABLES S.A.": 1.10,
  "SILVIA ESTER GONZALEZ": 1.12,
  "SINERGIUM BIOTECH SA": 1.10,
  "SINTEPLAST SOCIEDAD ANONIMA": 1.10,
  "SODECAR SA": 1.20,
  "SOL MINERALES Y SERVICIOS SA": 1.21,
  "SPIRAX SARCO S A": 1.18,
  "SUAVESTAR S.A.": 1.10,
  "SUCESORES DE ALFREDO WILLINER S A": 1.15,
  "SUPERCEMENTO SAIC - ROVELLA CARRANZA SA - 2DO ACUED P INTERIOR CHACO U T": 1.10,
  "TANDANOR SACI Y N": 1.28,
  "TECHINT COMPAÑIA TECNICA INTERNACIONAL SOCIEDAD ANONIMA COMERCIAL E INDUSTRIAL": 1.15,
  "TECHINT CTI SACI - SACDE SA - UTE": 1.15,
  "TECHINT SACEI SACDE S.A. ARGENTINA DE CONSTRUCCION Y DESARROLLO UTE": 1.15,
  "TECHINT SAIC": 1.15,
  "TECHNIA S A": 1.10,
  "TECNOLOGIA ARGENTINA EN CINTAS SA T A C S A": 1.11,
  "TECNOTAR SA": 1.21,
  "TECPETROL S A": 1.21,
  "TERNIUM ARGENTINA S A": 1.21,
  "TETRA DE ARGENTINA S.R.L.": 1.05,
  "TIGRE ARGENTINA S. A.": 1.11,
  "TOYOTA ARGENTINA S A": 1.15,
  "TUBOSCOPE VETCO DE ARGENTINA S A": 1.15,
  "TYC  S.A": 1.10,
  "UT MINERA SAL DE LOS ANGELES - POTASIO Y LITIO DE ARGENTINA SA - SALTA EXPLORACIONES SA": 1.21,
  "VARTECO QUIMICA PUNTANA S A": 1.10,
  "VEOLIA SERVICIOS Y GESTION DE ENERGIA ARGENTINA S.A.U": 1.11,
  "VEOLIA WATER TECHNOLOGIES ARGENTINA S.A.": 1.11,
  "VICENTE TRAPANI S.A.": 1.21,
  "VICENTIN S.A.I.C.": 1.21,
  "YKK ARGENTINA SOCIEDAD ANONIMA": 1.10,
  "YPF ENERGIA ELECTRICA S.A.": 1.30,
  "YPF GAS S.A.": 1.30,
}

/**
 * Normaliza una razón social para comparación:
 * - Minúsculas
 * - Quita puntos (S.A. → SA, S.R.L. → SRL)
 * - Colapsa espacios múltiples en uno solo
 * - Trim
 */
function normalize(str: string): string {
  return str.toLowerCase().replace(/\./g, '').replace(/\s+/g, ' ').trim()
}

/**
 * Busca el multiplicador de precio para un cliente por su razón social.
 * Estrategia de búsqueda:
 * 1. Exacto (case sensitive)
 * 2. Normalizado (sin puntos, espacios colapsados, case insensitive)
 * 3. Parcial normalizado (contiene)
 *
 * @param razonSocial - Razón social del cliente (como viene de Colppy)
 * @returns El multiplicador si se encuentra, o 1.0 por defecto
 */
export function getMultiplierForClient(razonSocial: string): number {
  if (!razonSocial) return 1.0

  // 1. Búsqueda exacta (case sensitive)
  if (CLIENT_MULTIPLIERS[razonSocial]) {
    return CLIENT_MULTIPLIERS[razonSocial]
  }

  // 2. Búsqueda normalizada (sin puntos, espacios colapsados, case insensitive)
  const normalizedRazon = normalize(razonSocial)
  const normalizedKey = Object.keys(CLIENT_MULTIPLIERS).find(
    k => normalize(k) === normalizedRazon
  )
  if (normalizedKey) {
    return CLIENT_MULTIPLIERS[normalizedKey]
  }

  // 3. Búsqueda parcial normalizada (contiene)
  const partialKey = Object.keys(CLIENT_MULTIPLIERS).find(
    k => normalizedRazon.includes(normalize(k)) ||
         normalize(k).includes(normalizedRazon)
  )
  if (partialKey) {
    return CLIENT_MULTIPLIERS[partialKey]
  }

  // Default: sin markup
  return 1.0
}
